"""codeforces ratings

Revision ID: 179cb2ab2579
Revises: b933c89ae7fd
Create Date: 2020-09-09 07:34:45.319414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179cb2ab2579'
down_revision = 'b933c89ae7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cf_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cf_rating')
    # ### end Alembic commands ###
