"""codeforces id

Revision ID: b933c89ae7fd
Revises: 2554c26a5a75
Create Date: 2020-09-09 07:22:18.709119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b933c89ae7fd'
down_revision = '2554c26a5a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cf_id', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cf_id')
    # ### end Alembic commands ###
